/* eslint-disable @next/next/link-passhref */
/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Dashboard.module.css";
import Down from "../container/Down.js";
import Link from "next/link";
import Lines from "../public/threelines.jpg";
import { useState, useEffect } from "react";
function Dashboard() {
  const [st, setst] = useState(false);
  const [windowSize, setWindowSize] = useState({
    width: "",
    height: "",
  });
  useEffect(() => {
    // only execute all the code below in client side
    if (typeof window !== "undefined") {
      // Handler to call on window resize
      function handleResize() {
        // Set window width/height to state
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }

      // Add event listener
      window.addEventListener("resize", handleResize);

      // Call handler right away so state gets updated with initial window size
      handleResize();

      // Remove event listener on cleanup
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []); // Empty array ensures that effect is only run on mount
  return (
    <div>
      <Head>
        <title>Pat-Work with eampthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blacklogo.png" />
      </Head>
      <div className="w-full h-full bg-white left-0">
        <div className={st ? styles.box1 : styles.box}>
          {windowSize.width < 800 ? (
            <div
              onClick={() => {
                st ? setst(false) : setst(true);
              }}
              className={styles.nav}
              style={{ color: "white", background: "#3A3B3C" }}
            >
              <div className={styles.lines_box}>
                <Image src={Lines} alt="" />
              </div>
              <div className={styles.D_box}>
                Dasboard
              </div>
            </div>
          ) : (
            ""
          )}
          <div className={st ? styles.b1 : styles.b}>
            <div className={styles.image}>
              <img src="devender.jpg" alt="" />
            </div>
            <div className={styles.user_content}>
              <div>Devender</div>
              <div className={styles.down}>
                <Down />
              </div>
            </div>
            <div className={styles.hr}></div>
            <div className={styles.nav_content}>
              <div className={styles.active}>Dasboard</div>
              <Link href="/Worklog">
                <div className={styles.work}>Work Log</div>
              </Link>
              <Link href="/Timesheet">
                <div className={styles.work}>Time Sheet</div>
              </Link>
            </div>
          </div>
        </div>
        <div className={styles.left_content}>
          <div className={styles.written_box_1}>
            <div className={styles.written_content_3}>
              <div>Challenge</div>
            </div>
            <div className={styles.button}>
              <button>+ Challenge</button>
            </div>
          </div>
          <div className={styles.written_box_2}>
            <div className={styles.written_content_2}>
              <div>Working</div>
            </div>
            <div className={styles.challenge_box}>
              <div className={styles.challenge_box1}>
                <div className={styles.id}>DMFDP130322</div>
                <div className={styles.line}>
                  <hr />
                </div>
                <div>
                  <div>Estimation: 16hours</div>
                  <div>planning: Approval pending</div>
                  <div>Owner: Devender</div>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.written_box_3}>
            <div className={styles.written_content}>
              <div>Quality Check</div>
            </div>
          </div>
          <div className={styles.written_box_4}>
            <div className={styles.written_content_1}>
              <div>Done</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;

