/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/link-passhref */
import React from "react";
import Head from "next/head";
import Down from "../container/Down.js";
import Link from "next/link";
import styles from "../styles/Timesheet.module.css";
import Clock from "../container/Clock.js";
import Write from "../container/Write.js";

function Timesheet() {
  return (
    <div className="c">
      <Head>
        <title>PAT-Work with empathy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blacklogo.png" />
      </Head>
      <div className="box">
        <div className={styles.navbar}>
          <div className={styles.nav_content}>
            <Link href="/Dashboard">
              <div className={styles.nonactive}>Dashboard</div>
            </Link>
            <Link href="/Worklog">
              <div className={styles.nonactive}>Work Log</div>
            </Link>
            <Link href="/Timesheet">
              <div className={styles.active}>Timesheet</div>
            </Link>
          </div>
          <div className={styles.rightcontent} >
            <h3 className={styles.devender}style={{fontWeight:700, }}>Devender</h3>
            <img src="devender.jpg" alt="" />
            <Down className="cursor-pointer mr-10" />
          </div>
          <div className={styles.othercontent}>
            <div className={styles.imagecontainer}>
              <img src="timesheet.svg" alt="" />
            </div>
            <div className={styles.content}>
              <div className={styles.work_content}>
                <div className={styles.clock}>
                  <Clock />
                </div>
                <div className={styles.para}>
                  <p>
                    Great,You have logged 4 hours for DMFDP130322 in Analysing
                  </p>
                </div>
                <div className={styles.write}>
                  <Write />
                </div>
              </div>
              <div className={styles.table_content}>
                <div className={styles.last}>
                  <div>Last 3 days work log</div>
                </div>
                <table className={styles.table}>
                  <tr className={styles.tr}>
                    <th className={styles.td}>Challenge</th>
                    <th className={styles.td}>Date</th>
                    <th className={styles.td}>Time</th>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>50hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>94hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td} style={{ color: "blue" }}>Log Work</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                  <tr className={styles.tr}>
                    <td className={styles.td}>DMFDP130322</td>
                    <td className={styles.td}>04-06-2022</td>
                    <td className={styles.td}>67hours</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Timesheet;



